'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { authorizedApi } from '@/lib/api';
import type { AdminInvite, AdminUser, Me, Report } from '@/lib/types';

export function AdminDashboard() {
  const [me, setMe] = useState<Me | null>(null); const [invites, setInvites] = useState<AdminInvite[]>([]); const [reports, setReports] = useState<Report[]>([]); const [users, setUsers] = useState<AdminUser[]>([]); const [createdCode, setCreatedCode] = useState(''); const [message, setMessage] = useState('');
  async function refresh() { try { const identity = await authorizedApi<Me>('/me'); setMe(identity); if (identity.role === 'USER') return; const [inviteRows, reportRows, userRows] = await Promise.all([authorizedApi<AdminInvite[]>('/admin/invites'), authorizedApi<Report[]>('/admin/moderation'), authorizedApi<AdminUser[]>('/admin/users')]); setInvites(inviteRows); setReports(reportRows); setUsers(userRows); } catch (error) { setMessage(error instanceof Error ? error.message : 'Yönetim verileri alınamadı.'); } }
  useEffect(() => { authorizedApi<Me>('/me').then(async (identity) => { setMe(identity); if (identity.role === 'USER') return; const [inviteRows, reportRows, userRows] = await Promise.all([authorizedApi<AdminInvite[]>('/admin/invites'), authorizedApi<Report[]>('/admin/moderation'), authorizedApi<AdminUser[]>('/admin/users')]); setInvites(inviteRows); setReports(reportRows); setUsers(userRows); }).catch((error) => setMessage(error instanceof Error ? error.message : 'Yönetim verileri alınamadı.')); }, []);
  async function createInvite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const result = await authorizedApi<{ code: string }>('/admin/invites', { method: 'POST', body: JSON.stringify({ label: String(data.get('label') || '') || undefined, maxUses: Number(data.get('maxUses')) }) }); setCreatedCode(result.code); await refresh(); event.currentTarget.reset(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Davet oluşturulamadı.'); } }
  async function setStatus(id: string, status: 'ACTIVE' | 'SUSPENDED') { try { await authorizedApi(`/admin/users/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Durum güncellenemedi.'); } }
  if (message) return <main className="state-page"><h1>Yönetim ekranı açılamadı.</h1><p>{message}</p></main>;
  if (me?.role === 'USER') return <main className="state-page"><h1>Bu alan yalnız yönetim ekibine açık.</h1></main>;
  return <main className="admin-page"><header className="detail-hero"><div className="eyebrow">Yönetim</div><h1>Davetli beta kontrol merkezi</h1></header><section className="admin-grid"><article className="admin-panel"><h2>Davet kodları</h2>{me?.role === 'ADMIN' && <form className="inline-form" onSubmit={createInvite}><input name="label" placeholder="Etiket" maxLength={80} /><input name="maxUses" type="number" min="1" max="10000" defaultValue="10" aria-label="Kullanım kotası" /><button className="primary-button">Oluştur</button></form>}{createdCode && <p className="secret-result">Yeni kod: <strong>{createdCode}</strong><br />Bu değer tekrar gösterilmez.</p>}<div className="table-list">{invites.map((invite) => <div key={invite.id}><span>{invite.prefix}… {invite.label}</span><b>{invite.useCount}/{invite.maxUses}</b></div>)}</div></article><article className="admin-panel"><h2>Açık şikâyetler</h2><div className="table-list">{reports.length ? reports.map((report) => <div key={report.id}><span>{report.targetType}: {report.reason}</span><b>{report.status}</b></div>) : <p>Açık şikâyet yok.</p>}</div></article><article className="admin-panel full-panel"><h2>Kullanıcılar</h2><div className="table-list">{users.map((user) => <div key={user.id}><span>{user.profile?.displayName ?? user.email}<small>{user.role} · {user.status}</small></span>{me?.role === 'ADMIN' && user.id !== me.id && <button className="text-button" onClick={() => setStatus(user.id, user.status === 'SUSPENDED' ? 'ACTIVE' : 'SUSPENDED')}>{user.status === 'SUSPENDED' ? 'Geri aç' : 'Askıya al'}</button>}</div>)}</div></article></section></main>;
}
